/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 11-Apr-2019 11:08:23
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\gongju\matlab\R2016a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
  0.0009770387239924,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  0.0009592899785809,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  0.0009446918438402,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  0.0009343612962782,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
  0.0009290203026529,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.976637732433,   0.9805458873287 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.940730414716,   0.9445675746307 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.911197067426,   0.9149758348014 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.890297435092,    0.894034880277 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.879492121782,   0.8832082029929 
  },
  {
                   1,                 0,                 0 
  }
};
